import type { Metadata } from 'next';
import './globals.css';
import { homePath, ticketsPath } from '@/paths';
import Link from 'next/link';
import { Button, buttonVariants } from '@/components/ui/button';
import { LucideKanban } from 'lucide-react';
import { Header } from '@/components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <main
          className='
            min-h-screen flex-1
            overflow-y-auto overflow-x-hidden
            py-24 px-8
            bg-secondary/20
            flex flex-col
          '
        >
          {children}
        </main>
      </body>
    </html>
  );
}
