import type { Metadata } from 'next';
import './globals.css';
import { homePath, ticketsPath } from '@/paths';
import Link from 'next/link';
import { Button, buttonVariants } from '@/components/ui/button';
import { LucideKanban } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <nav
          className='
            supports-backdropblur:bg-background/60
            fixed left-0 right-0 top-0 z-20
            border-b bg-background/95 backdrop-blur
            w-full flex py-2.5 px-5 justify-between
            '
        >
          <div>
            <Link
              href={homePath()}
              className={buttonVariants({ variant: 'ghost' })}
            >
              <LucideKanban />
              <h1 className='text-lg font-semibold'>Ticket Bounty</h1>
            </Link>
          </div>
          <div>
            <Link
              href={ticketsPath()}
              className={buttonVariants({ variant: 'default' })}
            >
              Tickets
            </Link>
          </div>
        </nav>
        <main
          className='
            min-h-screen flex-1
            overflow-y-auto overflow-x-hidden
            py-24 px-8
            bg-secondary/20
            flex flex-col
            '
        >
          {children}
        </main>
      </body>
    </html>
  );
}
